# 워크플로우 이름을 Node.js CI로 지정
name : Node.js CI

# 어떤 이벤트가 발생했을 때 워크플로우를 실행할지 정의
on:
  push: 
    branches:
      - main
    pull_request:
      branches:
        - main

# 실행할 작업을 정의하는 영역
jobs:
  bulid: # 작업 이름을 build로 지정
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x,20.x,22.x]

    steps:
      - name : Checkout repository
        uses: actions/checkout@v2
      
      - name : Setup Node.js
        usees: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name : Install dependencies
        run: npm install

      - name : Run tests
        run: npm test